config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  devise_scope :user do
    authenticated :user do
      root 'products#index'
    end
    unauthenticated do
      root 'devise/sessions#new'
    end
  end

  resources :products, only: %i[index show]
  resources :payment_transactions, only: %i[create show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/payment_transaction.rb
class PaymentTransaction < ApplicationRecord
  belongs_to :product
  belongs_to :user

  validates :amount, :user, :product, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :payment_transactions, dependent: :destroy

  validates :title, :description, :price, presence: true
  validates :title, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:stripe_connect]

  has_many :payment_transactions, dependent: :destroy

  validates :stripe_user_id,
            exclusion: { in: [Rails.application.credentials.stripe[:owner_stripe_user_id]] }

  def self.seller
    User.where.not(stripe_user_id: nil).take
  end

  def can_become_seller?
    !stripe_user_id && User.where.not(stripe_user_id: nil).empty?
  end

  def seller?
    stripe_user_id.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def authenticate_seller!
    redirect_to root_path unless current_user.seller?
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def stripe_connect
    auth_data = request.env['omniauth.auth']
    if current_user.update(stripe_user_id: auth_data['uid'])
      flash[:notice] = 'Stripe Account connected'
      redirect_to admin_root_path
    else
      flash[:alert] = 'Sorry, but you can not become seller'
      redirect_to root_path
    end
  end

  def failure
    flash[:alert] = params['error_description']
    redirect_to root_path
  end
end

app/controllers/payment_transactions_controller.rb
class PaymentTransactionsController < ApplicationController
  def create
    @payment_transaction = PaymentService.call(payment_transaction_params,
                                               params[:stripeToken]).result
    redirect_to payment_transaction_path(@payment_transaction)
  end

  def show
    @payment_transaction = current_user.payment_transactions.find(params[:id])
  end

  private

  def payment_transaction_params
    params.require(:payment_transaction).permit(:user_id, :amount, :product_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' unless devise_error_messages?

    messages = resource.errors.full_messages.map { |msg| content_tag(:p, msg) }.join

    html = <<-HTML
    <div id='flash'>
      <div class="popup_status alert">#{messages}</div>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    !resource.errors.empty?
  end
end

app/helpers/money_helper.rb
module MoneyHelper
  def to_cents(amount)
    (amount * 100).round
  end
end

app/views/layouts/_flash_messages.html.slim
#flash
  - flash.each do |name, messages|
    .popup_status class=name
      - if messages.is_a? Array
        - messages.each do |message|
          p= message
      - else
        = messages

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed aria-expanded='false' data-target='#bs-navbar' data-toggle='collapse' type='button'
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
    #bs-navbar.collapse.navbar-collapse
      - if user_signed_in?
        ul.nav.navbar-nav
          li
            = link_to 'HOME', root_path
          - if current_user.seller?
            li
              = link_to 'ADMIN', admin_products_path
        ul.nav.navbar-nav.navbar-right
          li
            = link_to 'Sign Out', destroy_user_session_path, method: :delete
      - else
        ul.nav.navbar-nav.navbar-right
          li
            = link_to 'Sign In', new_user_session_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title RevvMarketplace
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/navbar'
    .container
      = render 'layouts/flash_messages'
      = yield

app/views/payment_transactions/_form.html.slim
- unless current_user.seller?
  - product ||= @product
  = form_for PaymentTransaction.new do |f|
    = f.hidden_field :user_id, value: current_user.id
    = f.hidden_field :amount, value: product.price
    = f.hidden_field :product_id, value: product.id
    script[src='https://checkout.stripe.com/checkout.js' class='stripe-button'
      data-key=Rails.application.credentials.stripe[:public_key]
      data-description=product.title
      data-amount=to_cents(product.price)
      data-locale= 'auto']

app/views/payment_transactions/show.html.slim
.container-fluid.full-height.vertical-center
  .row.justify-content-center
    .card.checkout-complete-card
      .card-body.text-center
        div
          h2 Thank you for your payment!
          p
            span Your Payment number is
            strong<= @payment_transaction.id
          p
            span Paid:
            strong<= number_to_currency(@payment_transaction.amount)
          = link_to 'View product', product_path(@payment_transaction.product_id)

app/views/products/index.html.slim
.row.p-5
  .col-xs-12.col-sm-12.col-md-12.col-lg-12
    - if @products.any?
      table.table
        thead
          tr
            th.border-0.text-uppercase.small.font-weight-bold ID
            th.border-0.text-uppercase.small.font-weight-bold Item
            th.border-0.text-uppercase.small.font-weight-bold Description
            th.border-0.text-uppercase.small.font-weight-bold Price
            th.border-0.text-uppercase.small.font-weight-bold
        tbody
          - @products.each do |product|
            tr
              td= product.id
              td= link_to product.title, product_path(product)
              td= product.description
              td
                strong= number_to_currency(product.price)
              td= render 'payment_transactions/form', product: product
    - else
      .text-center
        h3 Sorry, no products yet :(
        br
        - if current_user.can_become_seller?
          h4 Maybe you would like become a seller?
          = link_to user_stripe_connect_omniauth_authorize_path, class: 'stripe-connect' do
            span Connect with Stripe

app/views/products/show.html.slim
.col-xs-12.col-sm-12.col-md-12.col-lg-12
  h1= @product.title
  p= @product.description
  strong= number_to_currency(@product.price)
  = render 'payment_transactions/form'